// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForInsertStageRuns implements pgx.CopyFromSource.
type iteratorForInsertStageRuns struct {
	rows                 []InsertStageRunsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertStageRuns) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertStageRuns) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].BuildID,
		r.rows[0].Name,
		r.rows[0].StartedAt,
		r.rows[0].DurationMs,
		r.rows[0].Result,
	}, nil
}

func (r iteratorForInsertStageRuns) Err() error {
	return nil
}

func (q *Queries) InsertStageRuns(ctx context.Context, arg []InsertStageRunsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"stage_run"}, []string{"build_id", "name", "started_at", "duration_ms", "result"}, &iteratorForInsertStageRuns{rows: arg})
}

// iteratorForInsertTestRuns implements pgx.CopyFromSource.
type iteratorForInsertTestRuns struct {
	rows                 []InsertTestRunsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertTestRuns) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertTestRuns) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].BuildID,
		r.rows[0].TestCaseID,
		r.rows[0].Outcome,
		r.rows[0].DurationMs,
		r.rows[0].RerunFailures,
		r.rows[0].FailureType,
		r.rows[0].FailureHash,
		r.rows[0].Stage,
	}, nil
}

func (r iteratorForInsertTestRuns) Err() error {
	return nil
}

func (q *Queries) InsertTestRuns(ctx context.Context, arg []InsertTestRunsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"test_run"}, []string{"build_id", "test_case_id", "outcome", "duration_ms", "rerun_failures", "failure_type", "failure_hash", "stage"}, &iteratorForInsertTestRuns{rows: arg})
}
