// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest.sql

package store

import (
	"context"
	"time"
)

const deleteStageRuns = `-- name: DeleteStageRuns :exec
DELETE FROM stage_run WHERE build_id = $1
`

func (q *Queries) DeleteStageRuns(ctx context.Context, buildID int64) error {
	_, err := q.db.Exec(ctx, deleteStageRuns, buildID)
	return err
}

const deleteTestRuns = `-- name: DeleteTestRuns :exec
DELETE FROM test_run WHERE build_id = $1
`

func (q *Queries) DeleteTestRuns(ctx context.Context, buildID int64) error {
	_, err := q.db.Exec(ctx, deleteTestRuns, buildID)
	return err
}

const ensureRepository = `-- name: EnsureRepository :one

INSERT INTO repository (name, default_branch)
VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

type EnsureRepositoryParams struct {
	Name          string
	DefaultBranch string
}

// Queries used by internal/ingest. All run inside one transaction per uploaded build.
// Returns the repository's id, creating it on first sight. An existing default branch is left unchanged.
func (q *Queries) EnsureRepository(ctx context.Context, arg EnsureRepositoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, ensureRepository, arg.Name, arg.DefaultBranch)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getBuildWithRepository = `-- name: GetBuildWithRepository :one
SELECT b.id, b.repository_id, b.job_name, b.build_number, b.branch, b.pr_number, b.commit_sha, b.result, b.started_at, b.finished_at, b.duration_ms, b.agent_name, b.agent_instance_type, b.agent_lifecycle, b.infra_failure, b.infra_reason, b.cost_usd, b.created_at, b.updated_at, b.tested_tree_sha, r.name AS repository_name
FROM build b
JOIN repository r ON r.id = b.repository_id
WHERE b.id = $1
`

type GetBuildWithRepositoryRow struct {
	Build          Build
	RepositoryName string
}

func (q *Queries) GetBuildWithRepository(ctx context.Context, id int64) (GetBuildWithRepositoryRow, error) {
	row := q.db.QueryRow(ctx, getBuildWithRepository, id)
	var i GetBuildWithRepositoryRow
	err := row.Scan(
		&i.Build.ID,
		&i.Build.RepositoryID,
		&i.Build.JobName,
		&i.Build.BuildNumber,
		&i.Build.Branch,
		&i.Build.PrNumber,
		&i.Build.CommitSha,
		&i.Build.Result,
		&i.Build.StartedAt,
		&i.Build.FinishedAt,
		&i.Build.DurationMs,
		&i.Build.AgentName,
		&i.Build.AgentInstanceType,
		&i.Build.AgentLifecycle,
		&i.Build.InfraFailure,
		&i.Build.InfraReason,
		&i.Build.CostUsd,
		&i.Build.CreatedAt,
		&i.Build.UpdatedAt,
		&i.Build.TestedTreeSha,
		&i.RepositoryName,
	)
	return i, err
}

type InsertStageRunsParams struct {
	BuildID    int64
	Name       string
	StartedAt  time.Time
	DurationMs int64
	Result     string
}

type InsertTestRunsParams struct {
	BuildID       int64
	TestCaseID    int64
	Outcome       string
	DurationMs    int64
	RerunFailures int32
	FailureType   *string
	FailureHash   *string
	Stage         string
}

const listStageRuns = `-- name: ListStageRuns :many
SELECT id, build_id, name, started_at, duration_ms, result FROM stage_run WHERE build_id = $1 ORDER BY started_at, id
`

func (q *Queries) ListStageRuns(ctx context.Context, buildID int64) ([]StageRun, error) {
	rows, err := q.db.Query(ctx, listStageRuns, buildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StageRun
	for rows.Next() {
		var i StageRun
		if err := rows.Scan(
			&i.ID,
			&i.BuildID,
			&i.Name,
			&i.StartedAt,
			&i.DurationMs,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestRuns = `-- name: ListTestRuns :many
SELECT tr.id, tr.outcome, tr.duration_ms, tr.rerun_failures, tr.failure_type, tr.failure_hash, tr.stage,
       tc.module, tc.class_name, tc.method_name
FROM test_run tr
JOIN test_case tc ON tc.id = tr.test_case_id
WHERE tr.build_id = $1
ORDER BY tc.class_name, tc.method_name
`

type ListTestRunsRow struct {
	ID            int64
	Outcome       string
	DurationMs    int64
	RerunFailures int32
	FailureType   *string
	FailureHash   *string
	Stage         string
	Module        string
	ClassName     string
	MethodName    string
}

func (q *Queries) ListTestRuns(ctx context.Context, buildID int64) ([]ListTestRunsRow, error) {
	rows, err := q.db.Query(ctx, listTestRuns, buildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTestRunsRow
	for rows.Next() {
		var i ListTestRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Outcome,
			&i.DurationMs,
			&i.RerunFailures,
			&i.FailureType,
			&i.FailureHash,
			&i.Stage,
			&i.Module,
			&i.ClassName,
			&i.MethodName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBuild = `-- name: UpsertBuild :one
INSERT INTO build (
    repository_id, job_name, build_number, branch, pr_number, commit_sha, tested_tree_sha, result,
    started_at, finished_at, duration_ms, agent_name, agent_instance_type, agent_lifecycle
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12,
    $13, $14
)
ON CONFLICT (job_name, build_number) DO UPDATE SET
    repository_id       = EXCLUDED.repository_id,
    branch              = EXCLUDED.branch,
    pr_number           = EXCLUDED.pr_number,
    commit_sha          = EXCLUDED.commit_sha,
    tested_tree_sha     = EXCLUDED.tested_tree_sha,
    result              = EXCLUDED.result,
    started_at          = EXCLUDED.started_at,
    finished_at         = EXCLUDED.finished_at,
    duration_ms         = EXCLUDED.duration_ms,
    agent_name          = EXCLUDED.agent_name,
    agent_instance_type = EXCLUDED.agent_instance_type,
    agent_lifecycle     = EXCLUDED.agent_lifecycle,
    updated_at          = now()
RETURNING id, (xmax = 0)::boolean AS inserted
`

type UpsertBuildParams struct {
	RepositoryID      int64
	JobName           string
	BuildNumber       int32
	Branch            string
	PrNumber          *int32
	CommitSha         string
	TestedTreeSha     *string
	Result            string
	StartedAt         time.Time
	FinishedAt        *time.Time
	DurationMs        *int64
	AgentName         *string
	AgentInstanceType *string
	AgentLifecycle    *string
}

type UpsertBuildRow struct {
	ID       int64
	Inserted bool
}

// Idempotent on (job_name, build_number): a second upload of the same build updates the row.
// (xmax = 0) is true only for a freshly inserted row, so the caller can answer 201 or 200.
// infra_failure, infra_reason and cost_usd are not set here: P3 and P4 compute them.
func (q *Queries) UpsertBuild(ctx context.Context, arg UpsertBuildParams) (UpsertBuildRow, error) {
	row := q.db.QueryRow(ctx, upsertBuild,
		arg.RepositoryID,
		arg.JobName,
		arg.BuildNumber,
		arg.Branch,
		arg.PrNumber,
		arg.CommitSha,
		arg.TestedTreeSha,
		arg.Result,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationMs,
		arg.AgentName,
		arg.AgentInstanceType,
		arg.AgentLifecycle,
	)
	var i UpsertBuildRow
	err := row.Scan(&i.ID, &i.Inserted)
	return i, err
}

const upsertTestCases = `-- name: UpsertTestCases :many
INSERT INTO test_case (repository_id, module, class_name, method_name)
SELECT $1::bigint, unnest($2::text[]), unnest($3::text[]), unnest($4::text[])
ON CONFLICT (repository_id, class_name, method_name) DO UPDATE SET module = EXCLUDED.module
RETURNING id, class_name, method_name
`

type UpsertTestCasesParams struct {
	RepositoryID int64
	Modules      []string
	ClassNames   []string
	MethodNames  []string
}

type UpsertTestCasesRow struct {
	ID         int64
	ClassName  string
	MethodName string
}

// One statement for all test cases of an upload; the arrays are zipped by unnest.
// The caller must pass each (class, method) once: ON CONFLICT cannot update one row twice in a statement.
// Several unnest() calls in one SELECT list advance together (PostgreSQL 10+), so the arrays are zipped by index.
func (q *Queries) UpsertTestCases(ctx context.Context, arg UpsertTestCasesParams) ([]UpsertTestCasesRow, error) {
	rows, err := q.db.Query(ctx, upsertTestCases,
		arg.RepositoryID,
		arg.Modules,
		arg.ClassNames,
		arg.MethodNames,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpsertTestCasesRow
	for rows.Next() {
		var i UpsertTestCasesRow
		if err := rows.Scan(&i.ID, &i.ClassName, &i.MethodName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
