// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID           int64
	Type         string
	BuildID      *int64
	RepositoryID int64
	Payload      []byte
	CreatedAt    time.Time
	PrCommentID  *int64
}

type Build struct {
	ID                int64
	RepositoryID      int64
	JobName           string
	BuildNumber       int32
	Branch            string
	PrNumber          *int32
	CommitSha         string
	Result            string
	StartedAt         time.Time
	FinishedAt        *time.Time
	DurationMs        *int64
	AgentName         *string
	AgentInstanceType *string
	AgentLifecycle    *string
	InfraFailure      bool
	InfraReason       *string
	CostUsd           pgtype.Numeric
	CreatedAt         time.Time
	UpdatedAt         time.Time
	TestedTreeSha     *string
}

type InfraEvent struct {
	ID         int64
	InstanceID string
	EventType  string
	EventTime  time.Time
	Raw        []byte
}

type Price struct {
	ID            int64
	InstanceType  string
	Lifecycle     string
	Region        string
	UsdPerHour    pgtype.Numeric
	EffectiveFrom time.Time
	Source        string
}

type Quarantine struct {
	ID                int64
	TestCaseID        int64
	State             string
	ReasonRule        string
	Evidence          []byte
	QuarantinedAt     time.Time
	ReleasedAt        *time.Time
	ConsecutivePasses int32
	Manual            bool
}

type Repository struct {
	ID            int64
	Name          string
	DefaultBranch string
	CreatedAt     time.Time
}

type StageRun struct {
	ID         int64
	BuildID    int64
	Name       string
	StartedAt  time.Time
	DurationMs int64
	Result     string
}

type TestCase struct {
	ID           int64
	RepositoryID int64
	Module       string
	ClassName    string
	MethodName   string
}

type TestRun struct {
	ID            int64
	BuildID       int64
	TestCaseID    int64
	Outcome       string
	DurationMs    int64
	RerunFailures int32
	FailureType   *string
	FailureHash   *string
	Stage         string
}
