// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quarantine.sql

package store

import (
	"context"
	"time"
)

const listActiveQuarantine = `-- name: ListActiveQuarantine :many
SELECT q.id, q.test_case_id, q.reason_rule, q.quarantined_at, q.manual,
       tc.module, tc.class_name, tc.method_name
FROM quarantine q
JOIN test_case tc ON tc.id = q.test_case_id
WHERE tc.repository_id = $1
  AND q.state = 'QUARANTINED'
ORDER BY q.quarantined_at, q.id
`

type ListActiveQuarantineRow struct {
	ID            int64
	TestCaseID    int64
	ReasonRule    string
	QuarantinedAt time.Time
	Manual        bool
	Module        string
	ClassName     string
	MethodName    string
}

// The tests currently quarantined in one repository, oldest first.
func (q *Queries) ListActiveQuarantine(ctx context.Context, repositoryID int64) ([]ListActiveQuarantineRow, error) {
	rows, err := q.db.Query(ctx, listActiveQuarantine, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveQuarantineRow
	for rows.Next() {
		var i ListActiveQuarantineRow
		if err := rows.Scan(
			&i.ID,
			&i.TestCaseID,
			&i.ReasonRule,
			&i.QuarantinedAt,
			&i.Manual,
			&i.Module,
			&i.ClassName,
			&i.MethodName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
